let allItems = [
    {
        name: 'baby',
        pluralName: 'babies',
        baseCost: 25,
        cps: 0.1,
        img: 'img/baby.png',
        owned: 0,
        cutsPooped: 0,
        description: 'Poops some tiny little cute cuts',
    },
    {
        name: 'dog',
        pluralName: 'dogs',
        baseCost: 200,
        cps: 3,
        img: 'img/dog.png',
        owned: 0,
        cutsPooped: 0,
        description: 'Keeps pooping around your house *bark *bark',
    },
    {
        name: 'neighbor',
        pluralName: 'neighbors',
        baseCost: 1200,
        cps: 10,
        img: 'img/neighbor.png',
        owned: 0,
        cutsPooped: 0,
        description: 'Always trying to poop more than you',
    },
    {
        name: 'Kingkongdara',
        baseCost: 30000,
        cps: 250,
        img: 'img/agu.png',
        owned: 0,
        cutsPooped: 0,
        description: 'Often leave a big nice cut in the toilet'
    },
    {
        name: 'Harry',
        baseCost: 270000,
        cps: 1000,
        img: 'img/harry.png',
        owned: 0,
        cutsPooped: 0,
        description: 'A bad ugly stupid boi who poops everyday',
    },
    {
        name: 'Cao Cao',
        baseCost: 1500000,
        cps: 5000,
        img: 'img/caocao.jpg',
        owned: 0,
        cutsPooped: 0,
        description: 'Chase people and make them poop',
    },
    {
        name: 'robot',
        pluralName: 'robots',
        baseCost: 40000000,
        cps: 33000,
        img: 'img/robot.png',
        owned: 0,
        cutsPooped: 0,
        description: 'Poops electronic components',
    },
]

export default allItems