let allItems = [
    {
        name: 'baby',
        pluralName: 'babies',
        baseCost: 25,
        cps: 0.1,
        img: 'img/baby.png',
        description: 'Poops some tiny little cute cuts',
        owned: 0,
    },
    {
        name: 'dog',
        pluralName: 'dogs',
        baseCost: 200,
        cps: 3,
        img: 'img/dog.png',
        description: 'Keeps pooping around your house *bark *bark',
        owned: 0,
    },
    {
        name: 'neighbor',
        pluralName: 'neighbors',
        baseCost: 1200,
        cps: 10,
        img: 'img/neighbor.png',
        description: 'Always want to poop more than you',
        owned: 0,
    },
    {
        name: 'human',
        pluralName: 'humans',
        baseCost: 30000,
        cps: 50,
        img: 'img/human.png',
        description: 'Just literally a normal human',
        owned: 0,
    },
    {
        name: 'Harry',
        baseCost: 270000,
        cps: 350,
        img: 'img/harry.png',
        description: 'A bad ugly stupid boi who poops everyday',
        owned: 0,
    },
    {
        name: 'Nikocado Avocado',
        baseCost: 4000000,
        cps: 2500,
        img: 'img/nikocado.jpg',
        description: 'He eats a lot, probably also poops a lot',
        owned: 0,
    },
    {
        name: 'Cao Cao',
        baseCost: 46000000,
        cps: 13000,
        img: 'img/caocao.jpg',
        description: 'Make people get diarrhea<br>Each Cao Cao boosts 0.1 CPS to every items unlocked',
        owned: 0,
    },
    {
        name: 'robot',
        pluralName: 'robots',
        baseCost: 330000000,
        cps: 100000,
        img: 'img/robot.png',
        description: 'Poops electronic components',
        owned: 0,
    },
    {
        name: 'hacker',
        baseCost: 5400000000,
        cps: 900000,
        pluralName: 'hackers',
        img: 'img/hacker.jpg',
        description: 'Hacks into everyone\'s toilet and steal their cuts',
        owned: 0,
    },
    {
        name: 'God',
        baseCost: 99999999999,
        cps: 9999999,
        img: 'img/god.jpg',
        description: 'God does poop, doesn\'t he?',
        owned: 0,
    },
]

export default allItems